BEGIN;

CREATE TABLE Kafedrs (
  ID_Kaf INT NOT NULL,
  Kaf_Name VARCHAR(255) NOT NULL
)

CREATE TABLE IF NOT EXISTS users(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    user_name VARCHAR(255) NOT NULL,
    chatID INT UNIQUE NOT NULL,
    ID_Kaf INT,
    FOREIGN KEY (ID_Kaf) REFERENCES Kafedrs(ID_Kaf)
)
COMMIT;